"""empty message

Revision ID: 1a74c172dd51
Revises: 
Create Date: 2022-08-23 23:20:43.404060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a74c172dd51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('immobile', sa.Column('validate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('immobile', 'validate')
    # ### end Alembic commands ###
